# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='replies_written',
            field=models.IntegerField(default=0),
        ),
    ]
